services:
  # db de etl
  mysql:
    image: mysql:8.0.44
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    hostname: ${MYSQL_HOST}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - airflow-net
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    hostname: ${POSTGRES_HOST}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - airflow-net

  # Anchor com '&anchor-name'
  airflow-common: &airflow-common
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.airflow
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - AIRFLOW__CORE__AUTH_MANAGER=airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - _AIRFLOW_DB_MIGRATE=true
      - AIRFLOW__CORE__TEST_CONNECTION=Enabled
      - AIRFLOW_CONN_MYSQL_DEFAULT=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    volumes:
      - ./airflow:/opt/airflow:Z
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      postgres:
        condition: service_healthy
      mysql:
        condition: service_started
    networks:
      - airflow-net

  init-airflow:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command: >
      -c "airflow db migrate && \
      airflow users create \
      --role Admin \
      --username ${AIRFLOW_USER_USERNAME} \
      --password ${AIRFLOW_USER_PASSWORD} \
      --firstname ${AIRFLOW_USER_FIRSTNAME} \
      --lastname ${AIRFLOW_USER_LASTNAME} \
      --email ${AIRFLOW_USER_EMAIL}"

  api-server:
    <<: *airflow-common
    command: api-server
    container_name: airflow-api-server
    ports:
      - "8080:8080"

  scheduler:
    <<: *airflow-common
    command: scheduler
    container_name: airflow-scheduler

  dag-processor:
    <<: *airflow-common
    command: dag-processor
    container_name: airflow-dag-processor

  triggerer:
    <<: *airflow-common
    command: triggerer
    container_name: airflow-triggerer

networks:
  airflow-net:
    driver: bridge

volumes:
  postgres:
  mysql:
