services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    hostname: postgres
    expose:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - airflow-net

  # Anchor com '&anchor-name'
  airflow-common: &airflow-common
    image: apache/airflow:3.1.7-python3.12
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__AUTH_MANAGER=airflow.providers.fab.auth_manager.fab_auth_manager.FabAuthManager
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - _AIRFLOW_DB_MIGRATE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
    volumes:
      - ./dags:/opt/airflow/dags:Z
      - ./logs:/opt/airflow/logs:Z
      - ./plugins:/opt/airflow/plugins:Z
    user: "${AIRFLOW_UID:-50000}:0"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - airflow-net

  api-server:
    <<: *airflow-common
    command: api-server
    container_name: airflow-api-server
    ports:
      - "8080:8080"

  scheduler:
    <<: *airflow-common
    command: scheduler
    container_name: airflow-scheduler

  dag-processor:
    <<: *airflow-common
    command: dag-processor
    container_name: airflow-dag-processor

  # triggerer:
  #   <<: *airflow-common
  #   command: triggerer
  #   container_name: airflow-triggerer

networks:
  airflow-net:
    driver: bridge

volumes:
  postgres:
